# Generated by Django 5.2.4 on 2025-07-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
