# Generated by Django 5.2.4 on 2025-07-29 16:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_event_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="presentationrequest",
            old_name="target_audience",
            new_name="skill_level",
        ),
    ]
