name: Build and Publish Docker Image

on:
  release:
    types: [created]
  workflow_dispatch:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-dev'
      - '[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+-rc'
      - '[0-9]+.[0-9]+.[0-9]+-rc.[0-9]+'
      - '[0-9]+.[0-9]+.[0-9]+'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME_LOWER: ${{ github.repository_owner }}/${{ github.event.repository.name }}

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract tag
        id: extract_tag
        run: |
          VERSION_TAG=${GITHUB_REF##*/}
          echo "version=$VERSION_TAG" >> "$GITHUB_OUTPUT"
          echo "image=ghcr.io/${{ env.IMAGE_NAME_LOWER }}" >> "$GITHUB_OUTPUT"

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: src/docker/Dockerfile
          push: true
          tags: |
            ${{ steps.extract_tag.outputs.image }}:${{ steps.extract_tag.outputs.version }}
            ${{ steps.extract_tag.outputs.image }}:latest
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.version=${{ steps.extract_tag.outputs.version }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Generate Release Notes
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.extract_tag.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate CHANGELOG.md
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: CHANGELOG.md
          tag: ${{ steps.extract_tag.outputs.version }}

      - name: Commit updated CHANGELOG.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update CHANGELOG.md for ${{ steps.extract_tag.outputs.version }}"
          branch: main
          file_pattern: CHANGELOG.md
