name: Dependency Vulnerability Scan

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pip_audit:
    runs-on: ubuntu-latest
    name: "pip-audit"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project
        run: pip install .

      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@v1.1.0
